
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://app:8080}
    image: healthtech-fe:latest
    container_name: healthtech-fe
    ports:
      - "3000:80"
    environment:
        - VITE_API_URL=http://app:8080
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - health-net

  app:
    build: ./backend
    container_name: healthtech-be
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL: jdbc:postgresql://healthtech-db:5432/healthtech
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=${TZ}
      - API_SECURITY_SECRET=${API_SECURITY_SECRET}
      - FRONTEND_URL=${FRONTEND_URL:-http://frontend:3000}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - health-net  
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB: mydb
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - health-net
volumes:
  pg-data:
networks:
  health-net:
    driver: bridge
