services:
  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - health-net

  flyway:
    env_file:
      - .env      
    image: flyway/flyway:9
    command: ${FLYWAY_COMMAND:-migrate}
    depends_on:
      - db
    networks:
      - health-net

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - health-net

volumes:
  pgdata:

networks:
  health-net:
