services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - health-net

  flyway:
    environment:
      FLYWAY_CLEAN_DISABLED: "false"
    image: flyway/flyway:9
    command: -url=jdbc:postgresql://db:5432/mydb -user=postgres -password=postgres clean
    depends_on:
      - db
    networks:
      - health-net

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env  
    ports:
      - "8080:8080"
    networks:
      - health-net

volumes:
  pgdata:

networks:
  health-net:
