-- Inserts SNOMED diagnosis codes into encounter_diagnosis_codes table

INSERT INTO encounter_codes (system, code, display, definition) VALUES
    ('http://snomed.info/sct', '404684003', 'Clinical finding (finding)', NULL),
    ('http://snomed.info/sct', '109006', 'Anxiety disorder of childhood OR adolescence', NULL),
    ('http://snomed.info/sct', '122003', 'Choroidal hemorrhage', NULL),
    ('http://snomed.info/sct', '127009', 'Spontaneous abortion with laceration of cervix', NULL),
    ('http://snomed.info/sct', '129007', 'Homoiothermia', NULL),
    ('http://snomed.info/sct', '134006', 'Decreased hair growth', NULL),
    ('http://snomed.info/sct', '140004', 'Chronic pharyngitis', NULL),
    ('http://snomed.info/sct', '144008', 'Normal peripheral vision', NULL),
    ('http://snomed.info/sct', '150003', 'Abnormal bladder continence', NULL),
    ('http://snomed.info/sct', '151004', 'Gonococcal meningitis', NULL),
    ('http://snomed.info/sct', '162004', 'Severe manic bipolar I disorder without psychotic features', NULL),
    ('http://snomed.info/sct', '165002', 'Accident-prone', NULL),
    ('http://snomed.info/sct', '168000', 'Typhlolithiasis', NULL),
    ('http://snomed.info/sct', '171008', 'Injury of ascending right colon without open wound into abdominal cavity', NULL),
    ('http://snomed.info/sct', '172001', 'Endometritis following molar AND/OR ectopic pregnancy', NULL),
    ('http://snomed.info/sct', '175004', 'Supraorbital neuralgia', NULL),
    ('http://snomed.info/sct', '177007', 'Poisoning by sawfly larvae', NULL),
    ('http://snomed.info/sct', '179005', 'Apraxia of dressing', NULL),
    ('http://snomed.info/sct', '181007', 'Hemorrhagic bronchopneumonia', NULL),
    ('http://snomed.info/sct', '183005', 'Autoimmune pancytopenia', NULL),
    ('http://snomed.info/sct', '184004', 'Withdrawal arrhythmia', NULL),
    ('http://snomed.info/sct', '188001', 'Injury of intercostal artery', NULL),
    ('http://snomed.info/sct', '192008', 'Congenital syphilitic hepatomegaly', NULL),
    ('http://snomed.info/sct', '193003', 'Benign hypertensive renal disease', NULL),
    ('http://snomed.info/sct', '198007', 'Disease due to Filoviridae', NULL),
    ('http://snomed.info/sct', '199004', 'Decreased lactation', NULL),
    ('http://snomed.info/sct', '216004', 'Delusion of persecution', NULL),
    ('http://snomed.info/sct', '219006', 'Alcohol user', NULL),
    ('http://snomed.info/sct', '222008', 'Acute epiglottitis with obstruction', NULL),
    ('http://snomed.info/sct', '223003', 'Tumor of body of uterus affecting pregnancy', NULL),
    ('http://snomed.info/sct', '228007', 'Lucio phenomenon', NULL),
    ('http://snomed.info/sct', '241006', 'Epilepsia partialis continua', NULL),
    ('http://snomed.info/sct', '242004', 'Noninfectious jejunitis', NULL),
    ('http://snomed.info/sct', '253005', 'Sycosis', NULL),
    ('http://snomed.info/sct', '257006', 'Acne rosacea, erythematous telangiectatic type', NULL),
    ('http://snomed.info/sct', '264008', 'Blind hypertensive eye', NULL),
    ('http://snomed.info/sct', '276008', 'Poisoning by oxytocin', NULL),
    ('http://snomed.info/sct', '279001', 'Senile myocarditis', NULL),
    ('http://snomed.info/sct', '281004', 'Dementia associated with alcoholism', NULL),
    ('http://snomed.info/sct', '282006', 'Acute myocardial infarction of basal-lateral wall', NULL),
    ('http://snomed.info/sct', '290006', 'Melnick-Fraser syndrome', NULL),
    ('http://snomed.info/sct', '292003', 'EEG finding', NULL),
    ('http://snomed.info/sct', '297009', 'Acute myringitis', NULL),
    ('http://snomed.info/sct', '299007', 'Paraffinoma of skin', NULL),
    ('http://snomed.info/sct', '303002', 'Apoplectic pancreatitis', NULL),
    ('http://snomed.info/sct', '308006', 'Pearly penile papules', NULL),
    ('http://snomed.info/sct', '310008', 'Boil of penis', NULL),
    ('http://snomed.info/sct', '313005', 'Déjà vu', NULL),
    ('http://snomed.info/sct', '317006', 'Reactive hypoglycemia', NULL),
    ('http://snomed.info/sct', '320003', 'Cervical dilatation, 1cm', NULL),
    ('http://snomed.info/sct', '324007', 'Plaster ulcer', NULL),
    ('http://snomed.info/sct', '330007', 'Occipital headache', NULL),
    ('http://snomed.info/sct', '335002', 'Pylorospasm', NULL),
    ('http://snomed.info/sct', '341009', 'ABO incompatibility reaction', NULL),
    ('http://snomed.info/sct', '349006', 'Absent tendon reflex', NULL),
    ('http://snomed.info/sct', '355001', 'Hemorrhagic shock', NULL),
    ('http://snomed.info/sct', '357009', 'Closed fracture of trapezoidal bone of wrist', NULL),
    ('http://snomed.info/sct', '359007', 'Kernicterus due to isoimmunization', NULL),
    ('http://snomed.info/sct', '360002', 'Acute radiation disease', NULL),
    ('http://snomed.info/sct', '364006', 'Acute left-sided heart failure', NULL),
    ('http://snomed.info/sct', '366008', 'Hidromeiosis', NULL),
    ('http://snomed.info/sct', '368009', 'Heart valve disorder', NULL),
    ('http://snomed.info/sct', '369001', 'Normal jugular venous pressure', NULL),
    ('http://snomed.info/sct', '378007', 'Morquio syndrome', NULL),
    ('http://snomed.info/sct', '382009', 'Legal history finding relating to child', NULL),
    ('http://snomed.info/sct', '383004', 'Passive range of hip extension - finding', NULL),
    ('http://snomed.info/sct', '385006', 'Secondary peripheral neuropathy', NULL),
    ('http://snomed.info/sct', '387003', 'Melanuria', NULL),
    ('http://snomed.info/sct', '398002', 'Left axis deviation greater than -90 degrees by EKG', NULL),
    ('http://snomed.info/sct', '407000', 'Congenital hepatomegaly', NULL),
    ('http://snomed.info/sct', '408005', 'Tooth chattering', NULL),
    ('http://snomed.info/sct', '409002', 'Food allergy diet', NULL),
    ('http://snomed.info/sct', '426008', 'Superficial injury of ankle without infection', NULL),
    ('http://snomed.info/sct', '431005', 'Hypertrophy of scrotum', NULL),
    ('http://snomed.info/sct', '437009', 'Abnormal composition of urine', NULL),
    ('http://snomed.info/sct', '440009', 'Persistent hyperphenylalaninemia', NULL),
    ('http://snomed.info/sct', '442001', 'Secondary hypopituitarism', NULL),
    ('http://snomed.info/sct', '443006', 'Cystocele affecting pregnancy', NULL),
    ('http://snomed.info/sct', '447007', 'Coach in sports activity accident', NULL),
    ('http://snomed.info/sct', '450005', 'Ulcerative stomatitis', NULL),
    ('http://snomed.info/sct', '452002', 'Blister of groin without infection', NULL),
    ('http://snomed.info/sct', '460001', 'Squamous metaplasia of prostate gland', NULL),
    ('http://snomed.info/sct', '467003', 'Old laceration of muscles of pelvic floor', NULL),
    ('http://snomed.info/sct', '470004', 'Vitreous touch syndrome', NULL),
    ('http://snomed.info/sct', '479003', 'Graves\\'' disease with pretibial myxedema AND with thyrotoxic crisis', NULL),
    ('http://snomed.info/sct', '486006', 'Acute vascular insufficiency', NULL),
    ('http://snomed.info/sct', '488007', 'Fibroid myocarditis', NULL),
    ('http://snomed.info/sct', '490008', 'Upper respiratory tract hypersensitivity reaction', NULL),
    ('http://snomed.info/sct', '496002', 'Closed traumatic dislocation of third cervical vertebra (disorder)', NULL),
    ('http://snomed.info/sct', '504009', 'Androgen-dependent hirsutism', NULL),
    ('http://snomed.info/sct', '517007', 'Foreign body in hypopharynx', NULL),
    ('http://snomed.info/sct', '518002', 'Multiple aggregation', NULL),
    ('http://snomed.info/sct', '520004', 'Congenital bent nose', NULL),
    ('http://snomed.info/sct', '527001', 'Spontaneous fetal evolution, Roederer\\''s method', NULL),
    ('http://snomed.info/sct', '536002', 'Glissonian cirrhosis', NULL),
    ('http://snomed.info/sct', '539009', 'Conjunctival argyrosis', NULL),
    ('http://snomed.info/sct', '547009', 'Hypersecretion of calcitonin', NULL),
    ('http://snomed.info/sct', '548004', '13p partial trisomy syndrome', NULL),
    ('http://snomed.info/sct', '554003', '2p partial trisomy syndrome', NULL),
    ('http://snomed.info/sct', '555002', 'Dicentra species poisoning', NULL),
    ('http://snomed.info/sct', '563001', 'Nystagmus', NULL),
    ('http://snomed.info/sct', '568005', 'Tic disorder', NULL);